# Generated by Django 3.0.2 on 2020-03-28 09:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_auto_20200325_1819'),
        ('cards', '0007_auto_20200327_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('reason', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='reason')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cards.Card', verbose_name='card')),
                ('lessons', models.ManyToManyField(related_name='refunds', to='lessons.Lesson', verbose_name='lessons')),
            ],
        ),
    ]
