# Generated by Django 3.0.2 on 2020-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='state',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default=0, verbose_name='state'),
        ),
    ]
