# Generated by Django 3.0.2 on 2020-04-21 12:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='test', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/', verbose_name='image'),
        ),
    ]
