# Generated by Django 3.0.2 on 2020-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200421_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateField(verbose_name='start at'),
        ),
    ]
