# Generated by Django 3.0.2 on 2020-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
