# Generated by Django 3.0.2 on 2020-04-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('promotions', '0003_auto_20200413_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPromotionCode',
            fields=[
                ('promotion_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apply', serialize=False, to='promotions.PromotionCode')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
