# Generated by Django 3.0.2 on 2020-04-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_remove_lesson_trainer'),
        ('core', '0004_temporaryleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Taught'), (1, 'Taught Instead')], default=0, verbose_name='state')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught', to='lessons.Lesson', verbose_name='lesson')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught', to='core.Trainer', verbose_name='trainer')),
            ],
        ),
    ]
