# Generated by Django 3.0.2 on 2020-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='taught_lessons',
            field=models.ManyToManyField(related_name='taught_lessons', through='lessons.TrainerLesson', to='lessons.Lesson', verbose_name='taught lessons'),
        ),
    ]
