# Generated by Django 3.0.2 on 2020-05-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('accounts', '0002_trainer_taught_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='taught_lessons',
            field=models.ManyToManyField(related_name='taught_trainer', through='lessons.TrainerLesson', to='lessons.Lesson', verbose_name='taught lessons'),
        ),
    ]
