# Generated by Django 3.0.2 on 2020-04-26 06:41

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200426_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='achievements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='achievements'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='introduction'),
        ),
    ]
