# Generated by Django 3.0.2 on 2020-02-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('card_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='class', verbose_name='image')),
                ('state', models.IntegerField(choices=[(0, 'Draft'), (2, 'Active'), (1, 'Inactive')], default=0, verbose_name='state')),
                ('level', models.IntegerField(choices=[(0, 'Basic Level'), (1, 'Intermediate Level'), (2, 'Advanced Level')], null=True, verbose_name='level')),
                ('price_per_lesson', models.FloatField(blank=True, null=True, verbose_name='price per lesson')),
                ('price_per_month', models.FloatField(blank=True, null=True, verbose_name='price per month')),
                ('price_course', models.FloatField(blank=True, null=True, verbose_name='price course')),
                ('max_people', models.IntegerField(blank=True, null=True, verbose_name='max people')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='start at')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='end at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('card_types', models.ManyToManyField(related_name='classes', to='card_types.CardType', verbose_name='card types')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Yoga Class',
                'verbose_name_plural': 'Yoga Classes',
                'ordering': ('created_at', 'name'),
            },
        ),
    ]
