# Generated by Django 3.0.2 on 2020-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_yogaclass_form_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='state'),
        ),
    ]
