# Generated by Django 3.0.2 on 2020-04-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200407_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='work_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='yoga_teaching_experience',
            new_name='experience',
        ),
    ]
