# Generated by Django 3.0.2 on 2020-04-11 08:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_auto_20200407_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='reason')),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default=0, verbose_name='state')),
                ('leave_at', models.DateField(verbose_name='leave at')),
                ('back_at', models.DateField(verbose_name='back at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
