# Generated by Django 3.0.2 on 2020-04-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_trainer'),
        ('teach', '0001_initial'),
        ('core', '0004_temporaryleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='taught_lessons',
            field=models.ManyToManyField(related_name='taught_lessons', through='teach.TrainerLesson', to='lessons.Lesson', verbose_name='taught lessons'),
        ),
    ]
