# Generated by Django 3.0.2 on 2020-06-11 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_trainer_taught_lessons'),
        ('card_invoices', '0001_initial'),
        ('cards', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinvoice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cards.Card', verbose_name='card'),
        ),
        migrations.AddField(
            model_name='cardinvoice',
            name='payment_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='classes.PaymentPeriod', verbose_name='payment period'),
        ),
        migrations.AddField(
            model_name='cardinvoice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_invoices', to='accounts.Staff', verbose_name='staff'),
        ),
    ]
