# Generated by Django 3.0.2 on 2020-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_invoices', '0002_auto_20200704_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinvoice',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Prepaid'), (1, 'Postpaid'), (2, 'Not specified')], default=0, verbose_name='payment type'),
        ),
    ]
