# Generated by Django 3.0.2 on 2020-06-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('card_invoices', '0002_auto_20200609_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinvoice',
            name='payment_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='classes.PaymentPeriod', verbose_name='payment period'),
        ),
    ]
