# Generated by Django 3.0.2 on 2020-05-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_invoices', '0002_cardinvoice_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinvoice',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Prepaid'), (1, 'Postpaid')], default=0, verbose_name='payment type'),
        ),
    ]
