# Generated by Django 3.0.2 on 2020-05-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200531_1123'),
        ('card_invoices', '0004_auto_20200531_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinvoice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_invoices', to='accounts.Staff', verbose_name='staff'),
        ),
    ]
