# Generated by Django 3.0.2 on 2020-05-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='min_lessons_require',
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='form_of_using',
            field=models.IntegerField(choices=[(0, 'Full Month'), (1, 'For Some Lessons'), (2, 'For Period Time Lessons'), (3, 'Trial'), (4, 'For Training Course')], default=0, verbose_name='form of using'),
        ),
    ]
