# Generated by Django 3.0.2 on 2020-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('core', '0001_initial'),
        ('trainer_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='taught_lessons',
            field=models.ManyToManyField(related_name='taught_lessons', through='trainer_lessons.TrainerLesson', to='lessons.Lesson', verbose_name='taught lessons'),
        ),
    ]
