# Generated by Django 3.0.2 on 2020-06-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200611_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='wages_per_lesson',
            field=models.FloatField(verbose_name='wages per lesson'),
        ),
    ]
