# Generated by Django 3.0.2 on 2020-07-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotiontype',
            unique_together={('promotion', 'category')},
        ),
    ]
