# Generated by Django 3.0.2 on 2020-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiontype',
            name='category',
            field=models.IntegerField(choices=[(0, 'Cash promotion'), (1, 'Percent promotion'), (2, 'Free some lesson promotion'), (3, 'Plus month practice promotion'), (4, 'Gift promotion')], verbose_name='category'),
        ),
    ]
