# Generated by Django 3.0.2 on 2020-04-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCodeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_code_products', to='shop.Product')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_code_products', to='promotions.PromotionCode')),
            ],
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='products',
            field=models.ManyToManyField(through='promotions.PromotionCodeProduct', to='shop.Product'),
        ),
    ]
