# Generated by Django 3.0.2 on 2020-04-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20200414_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontype',
            name='apply_any_product',
            field=models.BooleanField(default=False, verbose_name='apply any product'),
        ),
    ]
