# Generated by Django 3.0.2 on 2020-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotiontype_apply_any_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiontype',
            name='apply_any_product',
        ),
    ]
