# Generated by Django 3.0.2 on 2020-04-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('promotions', '0004_remove_promotiontype_apply_any_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('promotion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.PromotionType')),
            ],
        ),
        migrations.AddField(
            model_name='promotiontype',
            name='products',
            field=models.ManyToManyField(through='promotions.PromotionTypeProduct', to='shop.Product'),
        ),
    ]
