# Generated by Django 3.0.2 on 2020-04-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('promotions', '0005_auto_20200414_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiontype',
            name='products',
        ),
        migrations.AddField(
            model_name='promotiontype',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_types', to='shop.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='promotiontype',
            name='value',
            field=models.FloatField(verbose_name='value or quantity'),
        ),
        migrations.DeleteModel(
            name='PromotionTypeProduct',
        ),
    ]
