# Generated by Django 3.0.2 on 2020-05-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roll_calls', '0001_initial'),
        ('cards', '0001_initial'),
        ('classes', '0001_initial'),
        ('accounts', '0002_trainer_taught_lessons'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lessons',
            field=models.ManyToManyField(related_name='cards', through='roll_calls.RollCall', to='lessons.Lesson', verbose_name='lessons'),
        ),
        migrations.AddField(
            model_name='card',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.Trainee', verbose_name='trainee'),
        ),
        migrations.AddField(
            model_name='card',
            name='yogaclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='classes.YogaClass', verbose_name='yoga class'),
        ),
    ]
