# Generated by Django 3.0.2 on 2020-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
