# Generated by Django 3.0.2 on 2020-03-14 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20200314_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
