# Generated by Django 3.0.2 on 2020-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentperiod',
            name='end_at',
            field=models.DateField(verbose_name='end at'),
        ),
    ]
