# Generated by Django 3.0.2 on 2020-06-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='wages_per_lesson',
            field=models.FloatField(blank=True, null=True, verbose_name='wages per lesson'),
        ),
    ]
