# Generated by Django 3.0.2 on 2020-04-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
    ]
