# Generated by Django 3.0.2 on 2020-03-25 15:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200325_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendCardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lesson', models.IntegerField()),
                ('new_exprire_date', models.DateField(verbose_name='extend date')),
                ('reason', ckeditor_uploader.fields.RichTextUploadingField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_card_requests', to='cards.Card', verbose_name='card')),
            ],
        ),
    ]
