# Generated by Django 3.0.2 on 2020-03-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_extendcardrequest_number_of_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendcardrequest',
            old_name='new_exprire_date',
            new_name='new_expire_date',
        ),
    ]
