# Generated by Django 3.0.2 on 2020-03-27 07:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20200325_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendcardrequest',
            name='reason',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='reason'),
        ),
    ]
