# Generated by Django 3.0.2 on 2020-07-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainer_taught_lessons'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainerlesson',
            unique_together={('trainer', 'lesson')},
        ),
    ]
