# Generated by Django 3.0.2 on 2020-01-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('day', models.DateField(help_text='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time')),
                ('end_time', models.TimeField(help_text='Final time')),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='rooms.Room')),
                ('yogaclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.YogaClass')),
            ],
        ),
    ]
