# Generated by Django 3.0.2 on 2020-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='state')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='day')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='start time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='end time')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='content')),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='end at')),
            ],
        ),
    ]
