# Generated by Django 3.0.2 on 2020-04-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='trainer',
        ),
    ]
