# Generated by Django 3.0.2 on 2020-02-21 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_yogaclass_form_trainer'),
        ('lessons', '0001_initial'),
        ('core', '0001_initial'),
        ('roll_calls', '0001_initial'),
        ('cards', '0002_auto_20200221_0804'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cards',
            field=models.ManyToManyField(related_name='cards', through='roll_calls.RollCall', to='cards.Card', verbose_name='cards'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='rooms.Room', verbose_name='room'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.Trainer', verbose_name='trainer'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='yogaclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.YogaClass', verbose_name='yogaclass'),
        ),
    ]
