# Generated by Django 3.0.2 on 2020-02-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200225_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='is full'),
        ),
    ]
