# Generated by Django 3.0.2 on 2020-06-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roll_calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceApplication',
            fields=[
                ('roll_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='absence_application', serialize=False, to='roll_calls.RollCall')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
            ],
        ),
    ]
