# Generated by Django 3.0.2 on 2020-05-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceapplication',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='reason'),
        ),
    ]
